### ISSUE TITLE
用户登录LoginController中写clientManager.Login <- login无法被管道处理程序case login := <-manager.Login获到呢？

### ISSUE THREAD

**Issue by youngsailor** [SmallRuralDog/gf-websocket#1]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/30190732/194891772-480430e4-71d7-46d8-b363-bc4aa7e07a44.png">
请问断点以下好像执行不到，写入Login channel的数据也没有被case login := <- manager.Login获取到，为什么？

**Comment by zjfsdnu** [comment]
login的channel没有初始化 加上就好了
`Login:           make(chan *login, 1000),`
